//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDS.InventoryManagement.QBD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_INVSTK_TRCQB
    {
        public int InvStkID { get; set; }
        public string TRC_CODE { get; set; }
        public string TRC_Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string INV_GL { get; set; }
        public string COG_GL { get; set; }
    }
}
